In [1]:
import pandas as pd
import numpy as np

# Merging Rent & Sales 2019

In [2]:
#paths
rent19_bedroom_path = "Data/house_rent_sales/house_rent_0619_bedroom.csv"
rent19_dwelling_path = "Data/house_rent_sales/house_rent_0619_dwelling.csv"
rent19_overall_path = "Data/house_rent_sales/house_rent_0619_overall.csv"

sales19_dwelling_mean_path = "Data/house_rent_sales/house_sales_0319_dwelling_mean.csv"
sales19_dwelling_median_path = "Data/house_rent_sales/house_sales_0319_dwelling_median.csv"
sales19_overal_mean_path = "Data/house_rent_sales/house_sales_0319_overall_mean.csv"
sales19_overal_median_path = "Data/house_rent_sales/house_sales_0319_overall_median.csv"

In [3]:
#Load and merge data
rent19_bedroom = pd.read_csv(rent19_bedroom_path)
rent19_dwelling = pd.read_csv(rent19_dwelling_path)
rent19_overall = pd.read_csv(rent19_overall_path)

sales19_dwelling_mean = pd.read_csv(sales19_dwelling_mean_path)
sales19_dwelling_median = pd.read_csv(sales19_dwelling_median_path)
sales19_overal_mean = pd.read_csv(sales19_overal_mean_path)
sales19_overal_median = pd.read_csv(sales19_overal_median_path)

In [4]:
rent19 = rent19_bedroom.merge(rent19_dwelling, on=['LGA_CODE', 'LGA_NAME'], how='outer')
rent19 = rent19.merge(rent19_overall, on=['LGA_CODE', 'LGA_NAME'], how='outer')

sales19 = sales19_dwelling_mean.merge(sales19_dwelling_median, on=['LGA_CODE', 'LGA_NAME'], how='left')
sales19 = sales19.merge(sales19_overal_mean, on=['LGA_CODE', 'LGA_NAME'], how='left')
sales19 = sales19.merge(sales19_overal_median, on=['LGA_CODE', 'LGA_NAME'], how='left')

In [5]:
rent19.head()

,LGA_CODE,LGA_NAME,one_br,two_br,three_br,four_or_more_br,bedsitter,not_specified,flat,house,other,townhouse,weekly_rent_median
0,LGA10050,Albury,178.0,235.0,310.0,400.0,0.0,0.0,210.0,320.0,0.0,305.0,275.0
1,LGA10130,Armidale Regional,181.0,250.0,348.0,420.0,0.0,0.0,250.0,350.0,0.0,0.0,300.0
2,LGA10250,Ballina,298.0,380.0,500.0,625.0,0.0,0.0,370.0,573.0,380.0,465.0,478.0
3,LGA10470,Bathurst Regional,215.0,280.0,340.0,420.0,0.0,350.0,260.0,370.0,300.0,330.0,330.0
4,LGA10550,Bega Valley,210.0,300.0,360.0,440.0,0.0,0.0,300.0,360.0,0.0,360.0,350.0

In [6]:
rent19.columns

Index(['LGA_CODE', 'LGA_NAME', 'one_br', 'two_br', 'three_br',
       'four_or_more_br', 'bedsitter', 'not_specified', 'flat', 'house',
       'other', 'townhouse', 'weekly_rent_median'],
      dtype='object')

In [7]:
rent19.columns = ['LGA_CODE', 'LGA_NAME', 'r_one_br', 'r_two_br', 'r_three_br',
                  'r_four_or_more_br', 'r_bedsitter', 'r_not_specified', 'r_flat', 'r_house',
                  'r_other', 'r_townhouse', 'r_weekly_rent_median']

In [8]:
rent19.head()

,LGA_CODE,LGA_NAME,r_one_br,r_two_br,r_three_br,r_four_or_more_br,r_bedsitter,r_not_specified,r_flat,r_house,r_other,r_townhouse,r_weekly_rent_median
0,LGA10050,Albury,178.0,235.0,310.0,400.0,0.0,0.0,210.0,320.0,0.0,305.0,275.0
1,LGA10130,Armidale Regional,181.0,250.0,348.0,420.0,0.0,0.0,250.0,350.0,0.0,0.0,300.0
2,LGA10250,Ballina,298.0,380.0,500.0,625.0,0.0,0.0,370.0,573.0,380.0,465.0,478.0
3,LGA10470,Bathurst Regional,215.0,280.0,340.0,420.0,0.0,350.0,260.0,370.0,300.0,330.0,330.0
4,LGA10550,Bega Valley,210.0,300.0,360.0,440.0,0.0,0.0,300.0,360.0,0.0,360.0,350.0

In [9]:
sales19.columns

Index(['LGA_CODE', 'LGA_NAME', 'mean_nonstrata', 'mean_strata',
       'median_nonstrata', 'median_strata', 'mean_sales', 'median_sales'],
      dtype='object')

In [10]:
sales19.columns = ['LGA_CODE', 'LGA_NAME', 's_mean_nonstrata', 's_mean_strata',
                   's_median_nonstrata', 's_median_strata', 's_mean_sales', 's_median_sales']

In [11]:
sales19.head()

,LGA_CODE,LGA_NAME,s_mean_nonstrata,s_mean_strata,s_median_nonstrata,s_median_strata,s_mean_sales,s_median_sales
0,LGA10050,Albury,370.0,205.0,352.0,212.0,340,320
1,LGA10130,Armidale Regional,362.0,0.0,360.0,0.0,355,350
2,LGA10250,Ballina,698.0,536.0,640.0,515.0,635,577
3,LGA10300,Balranald,0.0,0.0,0.0,0.0,0,0
4,LGA10470,Bathurst Regional,457.0,289.0,435.0,310.0,440,425

In [12]:
rent_sales19 = sales19.merge(rent19, on=['LGA_CODE', 'LGA_NAME'], how='outer')

In [13]:
rent_sales19.head()

,LGA_CODE,LGA_NAME,s_mean_nonstrata,s_mean_strata,s_median_nonstrata,s_median_strata,s_mean_sales,s_median_sales,r_one_br,r_two_br,r_three_br,r_four_or_more_br,r_bedsitter,r_not_specified,r_flat,r_house,r_other,r_townhouse,r_weekly_rent_median
0,LGA10050,Albury,370.0,205.0,352.0,212.0,340.0,320.0,178.0,235.0,310.0,400.0,0.0,0.0,210.0,320.0,0.0,305.0,275.0
1,LGA10130,Armidale Regional,362.0,0.0,360.0,0.0,355.0,350.0,181.0,250.0,348.0,420.0,0.0,0.0,250.0,350.0,0.0,0.0,300.0
2,LGA10250,Ballina,698.0,536.0,640.0,515.0,635.0,577.0,298.0,380.0,500.0,625.0,0.0,0.0,370.0,573.0,380.0,465.0,478.0
3,LGA10300,Balranald,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,LGA10470,Bathurst Regional,457.0,289.0,435.0,310.0,440.0,425.0,215.0,280.0,340.0,420.0,0.0,350.0,260.0,370.0,300.0,330.0,330.0

In [14]:
rent19.to_csv("Data/house_rent_sales/final/rent19_final.csv", index = None, header=True)
sales19.to_csv("Data/house_rent_sales/final/sales19_final.csv", index = None, header=True)
rent_sales19.to_csv("Data/house_rent_sales/final/rent19_sales19_final.csv", index = None, header=True)

# Merging Rent & Sales 2017

In [15]:
#paths
rent17_bedroom_path = "Data/house_rent_sales/house_rent_0917_bedroom.csv"
rent17_dwelling_path = "Data/house_rent_sales/house_rent_0917_dwelling.csv"
rent17_overall_path = "Data/house_rent_sales/house_rent_0917_overall.csv"

sales17_dwelling_mean_path = "Data/house_rent_sales/house_sales_0617_dwelling_mean.csv"
sales17_dwelling_median_path = "Data/house_rent_sales/house_sales_0617_dwelling_median.csv"
sales17_overal_mean_path = "Data/house_rent_sales/house_sales_0617_overall_mean.csv"
sales17_overal_median_path = "Data/house_rent_sales/house_sales_0617_overall_median.csv"

In [16]:
#Load data
rent17_bedroom = pd.read_csv(rent17_bedroom_path)
rent17_dwelling = pd.read_csv(rent17_dwelling_path)
rent17_overall = pd.read_csv(rent17_overall_path)

sales17_dwelling_mean = pd.read_csv(sales17_dwelling_mean_path)
sales17_dwelling_median = pd.read_csv(sales17_dwelling_median_path)
sales17_overal_mean = pd.read_csv(sales17_overal_mean_path)
sales17_overal_median = pd.read_csv(sales17_overal_median_path)

In [17]:
# merging
rent17 = rent17_bedroom.merge(rent17_dwelling, on=['LGA_CODE', 'LGA_NAME'], how='outer')
rent17 = rent17.merge(rent17_overall, on=['LGA_CODE', 'LGA_NAME'], how='outer')

sales17 = sales17_dwelling_mean.merge(sales17_dwelling_median, on=['LGA_CODE', 'LGA_NAME'], how='left')
sales17 = sales17.merge(sales17_overal_mean, on=['LGA_CODE', 'LGA_NAME'], how='left')
sales17 = sales17.merge(sales17_overal_median, on=['LGA_CODE', 'LGA_NAME'], how='left')

In [18]:
rent17.columns

Index(['LGA_CODE', 'LGA_NAME', 'one_br', 'two_br', 'three_br',
       'four_or_more_br', 'bedsitter', 'not_specified', 'flat', 'house',
       'other', 'townhouse', 'weekly_rent_median'],
      dtype='object')

In [19]:
rent17.columns = ['LGA_CODE', 'LGA_NAME', 'r_one_br', 'r_two_br', 'r_three_br',
                  'r_four_or_more_br', 'r_bedsitter', 'r_not_specified', 'r_flat', 'r_house',
                  'r_other', 'r_townhouse', 'r_weekly_rent_median']

In [20]:
rent17.head()

,LGA_CODE,LGA_NAME,r_one_br,r_two_br,r_three_br,r_four_or_more_br,r_bedsitter,r_not_specified,r_flat,r_house,r_other,r_townhouse,r_weekly_rent_median
0,LGA10050,Albury,162.5,220.0,290.0,375.0,0.0,280.0,200.0,310.0,277.5,277.5,270.0
1,LGA10130,Armidale Regional,170.0,240.0,322.5,410.0,0.0,250.0,230.0,330.0,0.0,0.0,280.0
2,LGA10250,Ballina,240.0,360.0,470.0,580.0,0.0,460.0,350.0,510.0,415.0,455.0,450.0
3,LGA10470,Bathurst Regional,190.0,270.0,320.0,415.0,0.0,310.0,260.0,340.0,310.0,280.0,310.0
4,LGA10550,Bega Valley,205.0,270.0,350.0,400.0,0.0,0.0,265.0,355.0,350.0,330.0,320.0

In [21]:
sales17.columns

Index(['LGA_CODE', 'LGA_NAME', 'mean_nonstrata', 'mean_strata',
       'median_nonstrata', 'median_strata', 'mean_sales', 'median_sales'],
      dtype='object')

In [22]:
sales17.columns = ['LGA_CODE', 'LGA_NAME', 's_mean_nonstrata', 's_mean_strata',
                   's_median_nonstrata', 's_median_strata', 's_mean_sales', 's_median_sales']

In [23]:
sales17.head()

,LGA_CODE,LGA_NAME,s_mean_nonstrata,s_mean_strata,s_median_nonstrata,s_median_strata,s_mean_sales,s_median_sales
0,LGA10050,Albury,350.72904,197.23513,320.0,206.0,320.42552,290.0
1,LGA10130,Armidale Regional,372.99474,0.00000,352.5,0.0,361.56796,345.0
2,LGA10250,Ballina,695.14002,463.46875,639.5,424.0,616.27321,587.5
3,LGA10300,Balranald,0.00000,0.00000,0.0,0.0,0.00000,0.0
4,LGA10470,Bathurst Regional,436.94776,293.44444,417.0,280.0,426.22967,405.0

In [24]:
rent17_sales17 = sales17.merge(rent17, on=['LGA_CODE', 'LGA_NAME'], how='outer')

In [25]:
rent17_sales17.head()

,LGA_CODE,LGA_NAME,s_mean_nonstrata,s_mean_strata,s_median_nonstrata,s_median_strata,s_mean_sales,s_median_sales,r_one_br,r_two_br,r_three_br,r_four_or_more_br,r_bedsitter,r_not_specified,r_flat,r_house,r_other,r_townhouse,r_weekly_rent_median
0,LGA10050,Albury,350.72904,197.23513,320.0,206.0,320.42552,290.0,162.5,220.0,290.0,375.0,0.0,280.0,200.0,310.0,277.5,277.5,270.0
1,LGA10130,Armidale Regional,372.99474,0.00000,352.5,0.0,361.56796,345.0,170.0,240.0,322.5,410.0,0.0,250.0,230.0,330.0,0.0,0.0,280.0
2,LGA10250,Ballina,695.14002,463.46875,639.5,424.0,616.27321,587.5,240.0,360.0,470.0,580.0,0.0,460.0,350.0,510.0,415.0,455.0,450.0
3,LGA10300,Balranald,0.00000,0.00000,0.0,0.0,0.00000,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,LGA10470,Bathurst Regional,436.94776,293.44444,417.0,280.0,426.22967,405.0,190.0,270.0,320.0,415.0,0.0,310.0,260.0,340.0,310.0,280.0,310.0

In [26]:
rent17.to_csv("Data/house_rent_sales/final/rent17_final.csv", index = None, header=True)
sales17.to_csv("Data/house_rent_sales/final/sales17_final.csv", index = None, header=True)
rent17_sales17.to_csv("Data/house_rent_sales/final/rent17_sales17_final.csv", index = None, header=True)

# Combining Both Census Files

In [27]:
#paths
census1_path = "Data/census 2016/census2016_file01.csv"
census2_path = "Data/census 2016/census2016_file02.csv"

In [28]:
#Load data
census1 = pd.read_csv(census1_path)
census2 = pd.read_csv(census2_path)

In [29]:
census1.head()

,LGA_CODE,Age_below_15_yr,Age_15_64_yr,Age_over_65_yr,Age_below_15_yr_perc,Age_15_64_yr_perc,Age_over_65_yr_perc,BP_Aus,BP_Non_Aus,BP_Aus_Perc,...,P_Zimbabwe_Tot,P_Elsewhere_Tot,P_COB_NS_Tot,P_Y12e_Tot,P_Y11e_Tot,P_Y10e_Tot,P_Y9e_Tot,P_Y8b_Tot,P_DNGTS_Tot,P_Hghst_yr_schl_ns_Tot
0,LGA10050,9614,32328,9149,18.817404,63.275332,17.907264,41590,5540,88.245279,...,32,860,3949,16963,3968,9899,2784,1891,287,3840
1,LGA10130,5336,19126,4991,18.117000,64.937358,16.945642,23396,3631,86.565287,...,24,594,2425,12180,1094,4806,1352,1078,72,2306
2,LGA10250,6928,24398,10461,16.579319,58.386580,25.034102,33984,4609,88.057420,...,33,404,3195,14389,2033,9527,2451,1544,88,3287
3,LGA10300,479,1443,368,20.917031,63.013100,16.069869,1869,144,92.846498,...,0,20,281,503,192,414,167,180,15,248
4,LGA10470,8117,26406,6773,19.655657,63.943239,16.401104,34538,3565,90.643781,...,21,297,3195,13902,1795,8606,2055,1304,98,3806

In [30]:
# merging
census = census1.merge(census2, on=['LGA_CODE'], how='outer')

In [31]:
census.head()

,LGA_CODE,Age_below_15_yr,Age_15_64_yr,Age_over_65_yr,Age_below_15_yr_perc,Age_15_64_yr_perc,Age_over_65_yr_perc,BP_Aus,BP_Non_Aus,BP_Aus_Perc,...,Percent_Unem_loyment_P,Percnt_LabForc_prticipation_P,Percnt_Employment_to_populn_P,pct_pgrad,pct_grad_cert_dip,pct_bach_deg,pct_adv_dip,pct_cert_iii_iv,pct_cert_i_ii,pct_others
0,LGA10050,9614,32328,9149,18.817404,63.275332,17.907264,41590,5540,88.245279,...,6.8,59.3,55.2,4.264418,3.433529,19.155262,14.377647,33.944282,6.239818,18.585044
1,LGA10130,5336,19126,4991,18.117000,64.937358,16.945642,23396,3631,86.565287,...,7.7,55.4,51.1,12.040111,3.948824,22.717842,11.957123,24.080221,5.767635,19.488243
2,LGA10250,6928,24398,10461,16.579319,58.386580,25.034102,33984,4609,88.057420,...,5.9,53.2,50.1,4.923233,3.406270,21.761515,15.279949,29.327940,6.288499,19.012595
3,LGA10300,479,1443,368,20.917031,63.013100,16.069869,1869,144,92.846498,...,5.3,57.8,54.4,2.618454,1.620948,11.720698,9.975062,31.172070,5.610973,37.281796
4,LGA10470,8117,26406,6773,19.655657,63.943239,16.401104,34538,3565,90.643781,...,6.0,58.3,54.8,4.664509,3.163626,18.437316,13.105748,31.920738,6.592113,22.115951

In [32]:
census.to_csv("Data/census 2016/census_final.csv", index = None, header=True)

# Creating the Final Dataset for Analysis

In [33]:
#load transportation and nighttime lights
transpo_ntl = pd.read_csv("Data/transpo_ntl.csv")

In [34]:
transpo_ntl.head()

,LGA_CODE,land_area,bus_stop,coach_stop,light_rail,train_station,wharf,all_bus_stops,all_train_stations,all_transpo,ntl17_count,ntl17_min,ntl17_mean,ntl17_max,ntl17_sum,ntl19_count,ntl19_min,ntl19_mean,ntl19_max,ntl19_sum
0,LGA10050,305.9459,90.0,0.0,0.0,1.0,0.0,90.0,1.0,91.0,1766,0.14,2.375328,59.139999,4194.830078,1766,0.20,2.501557,56.820000,4417.750000
1,LGA10130,8620.6990,17.0,3.0,0.0,1.0,0.0,20.0,1.0,21.0,46613,-0.01,0.210830,34.509998,9827.399414,46614,0.05,0.234065,41.060001,10910.721680
2,LGA10250,484.9389,60.0,7.0,0.0,0.0,0.0,67.0,0.0,67.0,2576,0.09,0.619946,20.860001,1596.979980,2576,0.13,0.650873,23.889999,1676.650024
3,LGA10300,21690.6753,0.0,2.0,0.0,0.0,0.0,2.0,0.0,2.0,121835,0.07,0.201670,10.460000,24570.441406,121835,0.10,0.259825,10.840000,31655.767578
4,LGA10470,3817.8646,136.0,6.0,0.0,1.0,0.0,142.0,1.0,143.0,21325,0.06,0.334099,48.869999,7124.670410,21325,0.08,0.371763,46.009998,7927.839844

In [35]:
#merge all 17 files
final17 = rent17_sales17.merge(census, on=['LGA_CODE'], how='inner')

final17 = final17.merge(transpo_ntl, on=['LGA_CODE'], how='inner')

In [36]:
final17.shape

(126, 171)

In [37]:
list(final17.columns)

['LGA_CODE',
 'LGA_NAME',
 's_mean_nonstrata',
 's_mean_strata',
 's_median_nonstrata',
 's_median_strata',
 's_mean_sales',
 's_median_sales',
 'r_one_br',
 'r_two_br',
 'r_three_br',
 'r_four_or_more_br',
 'r_bedsitter',
 'r_not_specified',
 'r_flat',
 'r_house',
 'r_other',
 'r_townhouse',
 'r_weekly_rent_median',
 'Age_below_15_yr',
 'Age_15_64_yr',
 'Age_over_65_yr',
 'Age_below_15_yr_perc',
 'Age_15_64_yr_perc',
 'Age_over_65_yr_perc',
 'BP_Aus',
 'BP_Non_Aus',
 'BP_Aus_Perc',
 'BP_Non_Aus_Perc',
 'SE_Yr10_above',
 'SE_Yr9_below',
 'SE_Yr10_above_Perc',
 'SE_Yr9_below_Perc',
 'MS_Married',
 'MS_Separated',
 'MS_Divorced',
 'MS_Widowed',
 'MS_Never_Married',
 'MS_Single',
 'MS_Married_Perc',
 'MS_Separated_Perc',
 'MS_Divorced_Perc',
 'MS_Widowed_Perc',
 'MS_Never_Married_Perc',
 'MS_Single_Perc',
 'Median_age_persons',
 'Median_tot_prsnl_inc_weekly',
 'Median_tot_fam_inc_weekly',
 'Median_tot_hhd_inc_weekly',
 'Average_household_size',
 'P_Afghanistan_Tot',
 'P_Australia_Tot',
 'P_Bangladesh_Tot',
 'P_Bosnia_Herzegov_Tot',
 'P_Cambodia_Tot',
 'P_Canada_Tot',
 'P_Chile_Tot',
 'P_China_Tot',
 'P_Croatia_Tot',
 'P_Egypt_Tot',
 'P_England_Tot',
 'P_Fiji_Tot',
 'P_France_Tot',
 'P_Germany_Tot',
 'P_Greece_Tot',
 'P_Hong_Kong_Tot',
 'P_India_Tot',
 'P_Indonesia_Tot',
 'P_Iran_Tot',
 'P_Iraq_Tot',
 'P_Ireland_Tot',
 'P_Italy_Tot',
 'P_Japan_Tot',
 'P_Korea_South_Tot',
 'P_Lebanon_Tot',
 'P_Malaysia_Tot',
 'P_Malta_Tot',
 'P_Mauritius_Tot',
 'P_Myanmar_Tot',
 'P_Nepal_Tot',
 'P_Netherlands_Tot',
 'P_New_Zealand_Tot',
 'P_Nthern_Ireland_Tot',
 'P_Pakistan_Tot',
 'P_PNG_Tot',
 'P_Philippines_Tot',
 'P_Poland_Tot',
 'P_Scotland_Tot',
 'P_Singapore_Tot',
 'P_South_Africa_Tot',
 'P_SE_Europe_nfd_Tot',
 'P_Sri_Lanka_Tot',
 'P_Taiwan_Tot',
 'P_Thailand_Tot',
 'P_FYROM_Tot',
 'P_Turkey_Tot',
 'P_USA_Tot',
 'P_Vietnam_Tot',
 'P_Wales_Tot',
 'P_Zimbabwe_Tot',
 'P_Elsewhere_Tot',
 'P_COB_NS_Tot',
 'P_Y12e_Tot',
 'P_Y11e_Tot',
 'P_Y10e_Tot',
 'P_Y9e_Tot',
 'P_Y8b_Tot',
 'P_DNGTS_Tot',
 'P_Hghst_yr_schl_ns_Tot',
 'pct_no_pincome',
 'pct_pincome_1_499',
 'pct_pincome_500_999',
 'pct_pincome_1_999',
 'pct_pincome_1000_1499',
 'pct_pincome_1500_1999',
 'pct_pincome_1000_1999',
 'pct_pincome_2000_2999',
 'pct_pincome_3000_more',
 'pct_pincome_ns',
 'pct_no_fincome',
 'pct_fincome_1_499',
 'pct_fincome_500_999',
 'pct_fincome_1_999',
 'pct_fincome_1000_1499',
 'pct_fincome_1500_1999',
 'pct_fincome_1000_1999',
 'pct_fincome_2000_2999',
 'pct_fincome_3000_3999',
 'pct_fincome_4000_more',
 'pct_fincome_ns',
 'pct_no_hincome',
 'pct_hincome_1_499',
 'pct_hincome_500_999',
 'pct_hincome_1_999',
 'pct_hincome_1000_1499',
 'pct_hincome_1500_1999',
 'pct_hincome_1000_1999',
 'pct_hincome_2000_2999',
 'pct_hincome_3000_3999',
 'pct_hincome_4000_more',
 'pct_part_hincome',
 'pct_hincome_ns',
 'Percent_Unem_loyment_P',
 'Percnt_LabForc_prticipation_P',
 'Percnt_Employment_to_populn_P',
 'pct_pgrad',
 'pct_grad_cert_dip',
 'pct_bach_deg',
 'pct_adv_dip',
 'pct_cert_iii_iv',
 'pct_cert_i_ii',
 'pct_others',
 'land_area',
 'bus_stop',
 'coach_stop',
 'light_rail',
 'train_station',
 'wharf',
 'all_bus_stops',
 'all_train_stations',
 'all_transpo',
 'ntl17_count',
 'ntl17_min',
 'ntl17_mean',
 'ntl17_max',
 'ntl17_sum',
 'ntl19_count',
 'ntl19_min',
 'ntl19_mean',
 'ntl19_max',
 'ntl19_sum']

In [38]:
final17.dropna()

,LGA_CODE,LGA_NAME,s_mean_nonstrata,s_mean_strata,s_median_nonstrata,s_median_strata,s_mean_sales,s_median_sales,r_one_br,r_two_br,...,ntl17_count,ntl17_min,ntl17_mean,ntl17_max,ntl17_sum,ntl19_count,ntl19_min,ntl19_mean,ntl19_max,ntl19_sum
0,LGA10050,Albury,350.72904,197.23513,320.00,206.000,320.42552,290.00,162.5,220.0,...,1766,0.140000,2.375328,59.139999,4194.830078,1766,0.20,2.501557,56.820000,4417.750000
1,LGA10130,Armidale Regional,372.99474,0.00000,352.50,0.000,361.56796,345.00,170.0,240.0,...,46613,-0.010000,0.210830,34.509998,9827.399414,46614,0.05,0.234065,41.060001,10910.721680
2,LGA10250,Ballina,695.14002,463.46875,639.50,424.000,616.27321,587.50,240.0,360.0,...,2576,0.090000,0.619946,20.860001,1596.979980,2576,0.13,0.650873,23.889999,1676.650024
4,LGA10470,Bathurst Regional,436.94776,293.44444,417.00,280.000,426.22967,405.00,190.0,270.0,...,21325,0.060000,0.334099,48.869999,7124.670410,21325,0.08,0.371763,46.009998,7927.839844
5,LGA10550,Bega Valley,480.04897,292.83431,460.00,285.000,431.58223,420.00,205.0,270.0,...,36524,0.030000,0.198827,18.240000,7261.970215,36524,0.12,0.269662,14.730000,9849.149414
6,LGA10600,Bellingen,561.55357,0.00000,547.50,0.000,556.78947,545.00,0.0,300.0,...,8658,0.030000,0.213009,5.950000,1844.229980,8658,0.05,0.241115,5.160000,2087.570068
7,LGA10650,Berrigan,249.65000,0.00000,225.00,0.000,241.62121,222.50,0.0,167.5,...,11854,0.080000,0.237584,11.260000,2816.320312,11854,0.15,0.296548,12.440000,3515.280029
8,LGA10750,Blacktown,795.08317,550.45910,780.00,550.000,750.62768,737.00,280.0,380.0,...,1345,1.060000,16.021056,98.589996,21548.320312,1345,1.27,17.274647,90.900002,23234.400391
10,LGA10850,Blayney,324.76562,0.00000,271.75,0.000,324.76562,271.75,0.0,0.0,...,8530,0.110000,0.362831,111.339996,3094.950195,8530,0.14,0.395893,82.599998,3376.969971
11,LGA10900,Blue Mountains,710.50971,546.68333,685.00,510.000,702.10836,680.00,295.0,370.0,...,8030,0.120000,0.572665,25.510000,4598.500000,8030,0.11,0.572949,23.360001,4600.779785
15,LGA11250,Broken Hill,109.88418,0.00000,87.50,0.000,109.88418,87.50,185.0,200.0,...,928,0.130000,2.212759,46.439999,2053.439941,928,0.17,2.475550,44.799999,2297.310059
16,LGA11300,Burwood,8648.04734,848.74691,2460.00,852.000,4199.15062,1045.00,450.0,577.5,...,41,13.070000,23.528538,44.849998,964.670044,41,12.30,22.933171,45.779999,940.260010
17,LGA11350,Byron,1091.29730,838.82222,940.00,735.000,1018.46795,842.50,350.0,480.0,...,3008,0.070000,0.443979,17.950001,1335.489990,3008,0.13,0.473620,19.360001,1424.649902
18,LGA11400,Cabonne,372.15322,0.00000,345.00,0.000,372.15322,345.00,0.0,0.0,...,33530,0.060000,0.224264,17.299999,7519.580566,33530,0.14,0.278279,10.200000,9330.700195
19,LGA11450,Camden,784.61334,529.30882,750.00,520.000,773.54146,745.00,320.0,392.5,...,1124,0.360000,5.220240,56.540001,5867.549805,1124,0.39,6.211832,55.049999,6982.099609
20,LGA11500,Campbelltown,666.80582,484.79168,645.00,485.000,624.46107,620.00,280.0,350.0,...,1755,0.260000,5.200353,73.620003,9126.620117,1755,0.30,5.288051,70.449997,9280.530273
21,LGA11520,Canada Bay,2230.70880,1017.02949,2155.00,930.000,1430.40800,1250.00,510.0,650.0,...,114,6.980000,16.783596,48.950001,1913.329956,114,7.45,17.033861,54.450001,1941.860107
22,LGA11570,Canterbury-Bankstown,1105.96576,612.36991,1051.00,590.400,892.57362,863.00,390.0,430.0,...,618,2.480000,19.527186,79.529999,12067.800781,618,2.69,19.854126,83.970001,12269.849609
24,LGA11650,Central Coast,715.96414,521.10668,660.00,485.000,678.16296,635.00,270.0,350.0,...,9380,0.120000,1.350682,43.919998,12669.400391,9380,0.14,1.454965,54.000000,13647.569336
25,LGA11720,Cessnock,398.55139,286.34545,356.00,285.000,387.01620,349.00,200.0,280.0,...,10912,0.110000,0.515551,38.060001,5625.689941,10912,0.10,0.602383,61.910000,6573.200195
26,LGA11730,Clarence Valley,387.56543,408.55625,370.00,391.500,390.48082,372.50,215.0,280.0,...,55983,0.010000,0.200294,31.080000,11213.032227,55984,0.04,0.244708,20.270000,13699.730469
27,LGA11750,Cobar,182.04762,0.00000,175.00,0.000,182.04762,175.00,0.0,170.0,...,250222,0.050000,0.188472,33.430000,47159.773438,250222,0.09,0.242945,22.180000,60790.175781
28,LGA11800,Coffs Harbour,546.89154,356.17824,512.25,342.500,490.92133,459.00,260.0,320.0,...,6329,0.060000,0.558752,37.230000,3536.339844,6329,0.11,0.564456,29.490000,3572.439941
30,LGA12150,Coonamble,128.64286,0.00000,118.00,0.000,128.64286,118.00,0.0,0.0,...,53863,0.060000,0.206038,20.840000,11097.820312,53863,0.11,0.243784,14.770000,13130.940430
31,LGA13510,Gundagai,268.97614,0.00000,244.00,0.000,268.97614,244.00,140.0,200.0,...,22600,0.080000,0.239612,16.840000,5415.230469,22600,0.10,0.289835,18.610001,6550.279785
32,LGA12350,Cowra,225.25000,0.00000,214.00,0.000,225.25000,214.00,0.0,180.0,...,15746,0.080000,0.237439,21.150000,3738.720215,15746,0.12,0.287855,20.670000,4532.569824
33,LGA12380,Cumberland,979.63626,562.01750,912.50,560.000,777.61983,730.00,320.0,440.0,...,402,5.290000,26.825572,100.019997,10783.879883,402,5.91,26.847909,100.900002,10792.859375
34,LGA18230,Western Plains Regional,344.15301,310.70833,333.00,337.500,342.39276,333.00,180.0,250.0,...,41627,0.050000,0.302125,68.360001,12576.541016,41627,0.10,0.345774,55.630001,14393.529297
35,LGA12700,Dungog,594.27105,0.00000,525.00,0.000,594.27105,525.00,0.0,0.0,...,12425,0.040000,0.225131,6.870000,2797.250244,12425,0.11,0.264786,7.260000,3289.969727
36,LGA12730,Edward River,239.22000,0.00000,210.00,0.000,239.22000,210.00,120.0,190.0,...,50646,0.090000,0.220312,25.030001,11157.939453,50646,0.10,0.279544,18.150000,14157.799805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,LGA16490,Queanbeyan-Palerang Regional,626.49777,327.70337,620.00,335.000,527.27127,508.75,220.0,300.0,...,30402,0.050000,0.300726,54.480000,9142.679688,30402,0.07,0.370618,68.440002,11267.540039
93,LGA16550,Randwick,2459.81618,1051.17580,2295.00,972.000,1592.71260,1290.00,510.0,650.0,...,202,2.690000,26.445593,200.910004,5342.009766,202,2.31,27.185692,254.639999,5491.509766
94,LGA16610,Richmond Valley,307.71728,309.03333,292.00,290.000,307.92292,291.50,0.0,235.0,...,16257,0.010000,0.217273,18.820000,3532.209961,16257,0.10,0.266018,18.670000,4324.660156
95,LGA16700,Ryde,1889.12275,783.27084,1830.00,736.000,1205.04738,910.00,485.0,510.0,...,226,4.120000,18.446151,61.529999,4168.830078,226,4.29,19.117700,69.070000,4320.600098
96,LGA16900,Shellharbour,700.32386,507.74000,672.50,507.500,664.66019,635.00,0.0,350.0,...,839,0.210000,3.508856,29.879999,2943.930176,839,0.24,3.515780,30.540001,2949.739746
97,LGA16950,Shoalhaven,586.67697,408.10465,535.00,370.000,572.94064,525.00,200.0,300.0,...,25985,0.060000,0.351523,48.119999,9134.330078,25985,0.09,0.405833,41.790001,10545.580078
98,LGA17000,Singleton,481.82795,0.00000,447.00,0.000,462.31187,437.00,0.0,260.0,...,27096,0.100000,0.530647,128.470001,14378.409180,27096,0.09,0.624480,212.830002,16920.910156
99,LGA17040,Snowy Monaro Regional,357.05328,295.00000,290.00,310.000,340.01048,290.00,0.0,227.5,...,87731,0.010000,0.198220,25.520000,17390.080078,87731,0.08,0.258018,19.920000,22636.152344
100,LGA17080,Snowy Valleys,246.90984,0.00000,235.00,0.000,246.79839,237.50,0.0,220.0,...,51419,-0.040000,0.235431,36.020000,12105.629883,51419,0.09,0.275996,28.700001,14191.440430
101,LGA17100,Strathfield,2586.02222,682.29967,2420.00,680.000,1192.22536,720.00,450.0,530.0,...,79,9.980000,39.393926,130.820007,3112.120117,79,11.00,44.549369,161.279999,3519.400146
102,LGA17150,Sutherland Shire,1468.80414,875.85725,1350.00,820.000,1226.84750,1165.00,400.0,500.0,...,1879,0.290000,3.314710,42.169998,6228.339844,1879,0.32,3.525929,48.970001,6625.220215
103,LGA17200,Sydney,1890.66106,1020.53761,1780.00,935.000,1139.81761,1009.00,545.0,780.0,...,148,19.559999,52.469931,123.970001,7765.549805,148,15.62,60.586888,169.089996,8966.859375
104,LGA17310,Tamworth Regional,356.40033,296.07692,340.00,244.000,353.32502,333.00,180.0,250.0,...,53697,0.020000,0.249310,65.839996,13387.189453,53697,0.07,0.281622,60.790001,15122.230469
105,LGA17350,Temora,243.00000,0.00000,212.00,0.000,243.00000,212.00,0.0,0.0,...,15827,0.070000,0.216274,36.459999,3422.970459,15827,0.12,0.288303,31.320000,4562.969727
106,LGA17400,Tenterfield,263.88889,0.00000,252.50,0.000,263.88889,252.50,0.0,0.0,...,39031,0.020000,0.179328,12.610000,6999.340332,39031,0.03,0.215336,12.520000,8404.770508
107,LGA17420,The Hills Shire,1474.85386,830.81573,1365.00,855.000,1328.12517,1260.00,390.0,532.5,...,2171,0.170000,2.919664,66.510002,6338.589844,2171,0.22,3.331207,71.139999,7232.049805
108,LGA17550,Tweed,653.24866,415.45416,621.25,403.000,554.32615,530.00,250.0,360.0,...,6937,0.030000,0.578501,69.120003,4013.060059,6937,0.09,0.593414,45.459999,4116.510254
109,LGA17620,Upper Hunter Shire,332.90813,0.00000,312.50,0.000,332.90813,312.50,170.0,230.0,...,44484,0.040000,0.196535,12.770000,8742.670898,44484,0.05,0.239361,14.700000,10647.750000
110,LGA17640,Upper Lachlan Shire,376.44444,0.00000,331.25,0.000,376.44444,331.25,0.0,0.0,...,40285,0.060000,0.204251,11.810000,8228.240234,40285,0.06,0.248696,10.750000,10018.700195
111,LGA17650,Uralla,375.41176,0.00000,320.00,0.000,375.41176,320.00,0.0,0.0,...,17466,0.070000,0.194590,10.420000,3398.710205,17466,0.06,0.221280,10.780000,3864.880127
112,LGA17750,Wagga Wagga,376.11009,231.11905,357.00,247.000,365.15753,345.00,190.0,250.0,...,27503,0.080000,0.382738,46.099998,10526.449219,27503,0.12,0.416365,43.900002,11451.290039
116,LGA18020,Warrumbungle Shire,219.70588,0.00000,200.00,0.000,219.70588,200.00,0.0,0.0,...,67626,0.040000,0.194517,15.180000,13154.381836,67626,0.09,0.235636,11.420000,15935.142578
117,LGA18050,Waverley,3135.60396,1235.74564,2900.00,1152.500,1779.33116,1360.00,575.0,750.0,...,51,7.480000,17.844119,43.700001,910.050049,51,6.54,19.247451,46.369999,981.619995
119,LGA18200,Wentworth,230.15294,0.00000,212.00,0.000,228.09143,210.00,0.0,195.0,...,146893,0.030000,0.210557,70.360001,30929.304688,146893,0.08,0.257111,75.050003,37767.761719
120,LGA18250,Willoughby,2613.39276,1069.48095,2439.00,998.368,1805.13799,1580.00,550.0,675.0,...,126,2.080000,13.698492,51.049999,1726.010010,126,2.01,15.704206,55.610001,1978.729980
121,LGA18350,Wingecarribee,1020.11243,680.56897,870.00,511.000,986.62005,832.50,260.0,380.0,...,15191,0.070000,0.350656,29.790001,5326.820312,15191,0.06,0.416964,29.280001,6334.100098
122,LGA18400,Wollondilly,883.56434,0.00000,766.25,0.000,870.19774,755.00,0.0,350.0,...,14381,0.100000,0.399202,22.590000,5740.930176,14381,0.10,0.447346,42.759998,6433.279785
123,LGA18450,Wollongong,824.16162,573.67852,785.00,560.000,739.83750,680.00,290.0,390.0,...,3865,0.190000,3.592241,203.679993,13884.009766,3865,0.21,3.266282,161.899994,12624.179688
124,LGA18500,Woollahra,4169.68500,1822.74365,3625.00,1500.000,2758.40133,2225.00,515.0,737.5,...,69,3.760000,17.236668,46.400002,1189.330078,69,4.39,16.958841,46.209999,1170.160034
125,LGA18710,Yass Valley,614.15102,0.00000,542.50,0.000,609.59669,541.25,0.0,335.0,...,22715,0.060000,0.242194,21.180000,5501.430176,22715,0.11,0.329479,35.980000,7484.109375

In [39]:
final17.shape

(126, 171)

In [40]:
final17.to_csv("Data/final17_dataset.csv", index = None, header=True)